### PR TITLE
Rectangle List Fix (projection issues on right-aligned vertices)

### LINKED ISSUE #304: Fix rect lists
Still seem to be drawing wrong.

### PR DESCRIPTION
**Pull request by DrChat**
* Should fix #304

### CODE REVIEW

File: src/xenia/gpu/gl4/command_processor.cc [hunk 1]
```diff
@@ -335,7 +335,7 @@ bool CommandProcessor::SetupGL() {
       "    }\n"
       "    EmitVertex();\n"
       "    EndPrimitive();\n"
-      "  } else {\n"
+      "  } else if (gl_in[0].gl_Position.y == gl_in[1].gl_Position.y) {\n"
```
Comment (benvanik) [inline src/xenia/gpu/gl4/command_processor.cc]: what about the fall-through case? (if it's even possible?) this shader won't emit anything without the else

Comment (benvanik) [inline src/xenia/gpu/gl4/command_processor.cc]: (this may be ok, as the hardware may cull rects not matching these formats - just curious if you'd seen any missing rects in your experimenting)

Comment (DrChat) [inline src/xenia/gpu/gl4/command_processor.cc]: Yeah, it might be possible. If it falls through nothing will be drawn.

Depends on which will get our attention faster, no rects or corrupt rects on screen

**Comment by raven02** [comment]
Just tested it with another games - Dynasty Warriors Gundam 3-  that have rect list issue .It got fixed as well.

**Comment by benvanik** [comment]
SGTM!
